// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTagsIDParams creates a new GetTagsIDParams object
// with the default values initialized.
func NewGetTagsIDParams() *GetTagsIDParams {
	var ()
	return &GetTagsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTagsIDParamsWithTimeout creates a new GetTagsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTagsIDParamsWithTimeout(timeout time.Duration) *GetTagsIDParams {
	var ()
	return &GetTagsIDParams{

		timeout: timeout,
	}
}

// NewGetTagsIDParamsWithContext creates a new GetTagsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTagsIDParamsWithContext(ctx context.Context) *GetTagsIDParams {
	var ()
	return &GetTagsIDParams{

		Context: ctx,
	}
}

// NewGetTagsIDParamsWithHTTPClient creates a new GetTagsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTagsIDParamsWithHTTPClient(client *http.Client) *GetTagsIDParams {
	var ()
	return &GetTagsIDParams{
		HTTPClient: client,
	}
}

/*GetTagsIDParams contains all the parameters to send to the API endpoint
for the get tags ID operation typically these are written to a http.Request
*/
type GetTagsIDParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get tags ID params
func (o *GetTagsIDParams) WithTimeout(timeout time.Duration) *GetTagsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tags ID params
func (o *GetTagsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tags ID params
func (o *GetTagsIDParams) WithContext(ctx context.Context) *GetTagsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tags ID params
func (o *GetTagsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tags ID params
func (o *GetTagsIDParams) WithHTTPClient(client *http.Client) *GetTagsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tags ID params
func (o *GetTagsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get tags ID params
func (o *GetTagsIDParams) WithID(id int64) *GetTagsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get tags ID params
func (o *GetTagsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetTagsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
