// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTagsIDLogsParams creates a new GetTagsIDLogsParams object
// with the default values initialized.
func NewGetTagsIDLogsParams() *GetTagsIDLogsParams {
	var ()
	return &GetTagsIDLogsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTagsIDLogsParamsWithTimeout creates a new GetTagsIDLogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTagsIDLogsParamsWithTimeout(timeout time.Duration) *GetTagsIDLogsParams {
	var ()
	return &GetTagsIDLogsParams{

		timeout: timeout,
	}
}

// NewGetTagsIDLogsParamsWithContext creates a new GetTagsIDLogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTagsIDLogsParamsWithContext(ctx context.Context) *GetTagsIDLogsParams {
	var ()
	return &GetTagsIDLogsParams{

		Context: ctx,
	}
}

// NewGetTagsIDLogsParamsWithHTTPClient creates a new GetTagsIDLogsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTagsIDLogsParamsWithHTTPClient(client *http.Client) *GetTagsIDLogsParams {
	var ()
	return &GetTagsIDLogsParams{
		HTTPClient: client,
	}
}

/*GetTagsIDLogsParams contains all the parameters to send to the API endpoint
for the get tags ID logs operation typically these are written to a http.Request
*/
type GetTagsIDLogsParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get tags ID logs params
func (o *GetTagsIDLogsParams) WithTimeout(timeout time.Duration) *GetTagsIDLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tags ID logs params
func (o *GetTagsIDLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tags ID logs params
func (o *GetTagsIDLogsParams) WithContext(ctx context.Context) *GetTagsIDLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tags ID logs params
func (o *GetTagsIDLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tags ID logs params
func (o *GetTagsIDLogsParams) WithHTTPClient(client *http.Client) *GetTagsIDLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tags ID logs params
func (o *GetTagsIDLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get tags ID logs params
func (o *GetTagsIDLogsParams) WithID(id int64) *GetTagsIDLogsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get tags ID logs params
func (o *GetTagsIDLogsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetTagsIDLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
