// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTagsIDRunsParams creates a new GetTagsIDRunsParams object
// with the default values initialized.
func NewGetTagsIDRunsParams() *GetTagsIDRunsParams {
	var ()
	return &GetTagsIDRunsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTagsIDRunsParamsWithTimeout creates a new GetTagsIDRunsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTagsIDRunsParamsWithTimeout(timeout time.Duration) *GetTagsIDRunsParams {
	var ()
	return &GetTagsIDRunsParams{

		timeout: timeout,
	}
}

// NewGetTagsIDRunsParamsWithContext creates a new GetTagsIDRunsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTagsIDRunsParamsWithContext(ctx context.Context) *GetTagsIDRunsParams {
	var ()
	return &GetTagsIDRunsParams{

		Context: ctx,
	}
}

// NewGetTagsIDRunsParamsWithHTTPClient creates a new GetTagsIDRunsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTagsIDRunsParamsWithHTTPClient(client *http.Client) *GetTagsIDRunsParams {
	var ()
	return &GetTagsIDRunsParams{
		HTTPClient: client,
	}
}

/*GetTagsIDRunsParams contains all the parameters to send to the API endpoint
for the get tags ID runs operation typically these are written to a http.Request
*/
type GetTagsIDRunsParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get tags ID runs params
func (o *GetTagsIDRunsParams) WithTimeout(timeout time.Duration) *GetTagsIDRunsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tags ID runs params
func (o *GetTagsIDRunsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tags ID runs params
func (o *GetTagsIDRunsParams) WithContext(ctx context.Context) *GetTagsIDRunsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tags ID runs params
func (o *GetTagsIDRunsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tags ID runs params
func (o *GetTagsIDRunsParams) WithHTTPClient(client *http.Client) *GetTagsIDRunsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tags ID runs params
func (o *GetTagsIDRunsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get tags ID runs params
func (o *GetTagsIDRunsParams) WithID(id int64) *GetTagsIDRunsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get tags ID runs params
func (o *GetTagsIDRunsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetTagsIDRunsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
