// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetTagsIDRunsReader is a Reader for the GetTagsIDRuns structure.
type GetTagsIDRunsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTagsIDRunsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTagsIDRunsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetTagsIDRunsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTagsIDRunsOK creates a GetTagsIDRunsOK with default headers values
func NewGetTagsIDRunsOK() *GetTagsIDRunsOK {
	return &GetTagsIDRunsOK{}
}

/*GetTagsIDRunsOK handles this case with default header values.

Succesfully returned Runs.
*/
type GetTagsIDRunsOK struct {
}

func (o *GetTagsIDRunsOK) Error() string {
	return fmt.Sprintf("[GET /tags/{id}/runs][%d] getTagsIdRunsOK ", 200)
}

func (o *GetTagsIDRunsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTagsIDRunsNotFound creates a GetTagsIDRunsNotFound with default headers values
func NewGetTagsIDRunsNotFound() *GetTagsIDRunsNotFound {
	return &GetTagsIDRunsNotFound{}
}

/*GetTagsIDRunsNotFound handles this case with default header values.

No Runs found for this Tag.
*/
type GetTagsIDRunsNotFound struct {
}

func (o *GetTagsIDRunsNotFound) Error() string {
	return fmt.Sprintf("[GET /tags/{id}/runs][%d] getTagsIdRunsNotFound ", 404)
}

func (o *GetTagsIDRunsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
