// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetTagsIDLogsReader is a Reader for the GetTagsIDLogs structure.
type GetTagsIDLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTagsIDLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTagsIDLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetTagsIDLogsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTagsIDLogsOK creates a GetTagsIDLogsOK with default headers values
func NewGetTagsIDLogsOK() *GetTagsIDLogsOK {
	return &GetTagsIDLogsOK{}
}

/*GetTagsIDLogsOK handles this case with default header values.

Succesfully returned Logs.
*/
type GetTagsIDLogsOK struct {
}

func (o *GetTagsIDLogsOK) Error() string {
	return fmt.Sprintf("[GET /tags/{id}/logs][%d] getTagsIdLogsOK ", 200)
}

func (o *GetTagsIDLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTagsIDLogsNotFound creates a GetTagsIDLogsNotFound with default headers values
func NewGetTagsIDLogsNotFound() *GetTagsIDLogsNotFound {
	return &GetTagsIDLogsNotFound{}
}

/*GetTagsIDLogsNotFound handles this case with default header values.

No Logs found for this Tag.
*/
type GetTagsIDLogsNotFound struct {
}

func (o *GetTagsIDLogsNotFound) Error() string {
	return fmt.Sprintf("[GET /tags/{id}/logs][%d] getTagsIdLogsNotFound ", 404)
}

func (o *GetTagsIDLogsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
