// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SoftwareForScience/jiskefet-api-go/models"
)

// NewPatchTagsIDRunsParams creates a new PatchTagsIDRunsParams object
// with the default values initialized.
func NewPatchTagsIDRunsParams() *PatchTagsIDRunsParams {
	var ()
	return &PatchTagsIDRunsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchTagsIDRunsParamsWithTimeout creates a new PatchTagsIDRunsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchTagsIDRunsParamsWithTimeout(timeout time.Duration) *PatchTagsIDRunsParams {
	var ()
	return &PatchTagsIDRunsParams{

		timeout: timeout,
	}
}

// NewPatchTagsIDRunsParamsWithContext creates a new PatchTagsIDRunsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchTagsIDRunsParamsWithContext(ctx context.Context) *PatchTagsIDRunsParams {
	var ()
	return &PatchTagsIDRunsParams{

		Context: ctx,
	}
}

// NewPatchTagsIDRunsParamsWithHTTPClient creates a new PatchTagsIDRunsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchTagsIDRunsParamsWithHTTPClient(client *http.Client) *PatchTagsIDRunsParams {
	var ()
	return &PatchTagsIDRunsParams{
		HTTPClient: client,
	}
}

/*PatchTagsIDRunsParams contains all the parameters to send to the API endpoint
for the patch tags ID runs operation typically these are written to a http.Request
*/
type PatchTagsIDRunsParams struct {

	/*LinkRunToTagDto*/
	LinkRunToTagDto *models.LinkRunToTagDto
	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch tags ID runs params
func (o *PatchTagsIDRunsParams) WithTimeout(timeout time.Duration) *PatchTagsIDRunsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch tags ID runs params
func (o *PatchTagsIDRunsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch tags ID runs params
func (o *PatchTagsIDRunsParams) WithContext(ctx context.Context) *PatchTagsIDRunsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch tags ID runs params
func (o *PatchTagsIDRunsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch tags ID runs params
func (o *PatchTagsIDRunsParams) WithHTTPClient(client *http.Client) *PatchTagsIDRunsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch tags ID runs params
func (o *PatchTagsIDRunsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLinkRunToTagDto adds the linkRunToTagDto to the patch tags ID runs params
func (o *PatchTagsIDRunsParams) WithLinkRunToTagDto(linkRunToTagDto *models.LinkRunToTagDto) *PatchTagsIDRunsParams {
	o.SetLinkRunToTagDto(linkRunToTagDto)
	return o
}

// SetLinkRunToTagDto adds the linkRunToTagDto to the patch tags ID runs params
func (o *PatchTagsIDRunsParams) SetLinkRunToTagDto(linkRunToTagDto *models.LinkRunToTagDto) {
	o.LinkRunToTagDto = linkRunToTagDto
}

// WithID adds the id to the patch tags ID runs params
func (o *PatchTagsIDRunsParams) WithID(id int64) *PatchTagsIDRunsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch tags ID runs params
func (o *PatchTagsIDRunsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchTagsIDRunsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.LinkRunToTagDto != nil {
		if err := r.SetBodyParam(o.LinkRunToTagDto); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
