// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SoftwareForScience/jiskefet-api-go/models"
)

// NewPatchTagsIDLogsParams creates a new PatchTagsIDLogsParams object
// with the default values initialized.
func NewPatchTagsIDLogsParams() *PatchTagsIDLogsParams {
	var ()
	return &PatchTagsIDLogsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchTagsIDLogsParamsWithTimeout creates a new PatchTagsIDLogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchTagsIDLogsParamsWithTimeout(timeout time.Duration) *PatchTagsIDLogsParams {
	var ()
	return &PatchTagsIDLogsParams{

		timeout: timeout,
	}
}

// NewPatchTagsIDLogsParamsWithContext creates a new PatchTagsIDLogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchTagsIDLogsParamsWithContext(ctx context.Context) *PatchTagsIDLogsParams {
	var ()
	return &PatchTagsIDLogsParams{

		Context: ctx,
	}
}

// NewPatchTagsIDLogsParamsWithHTTPClient creates a new PatchTagsIDLogsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchTagsIDLogsParamsWithHTTPClient(client *http.Client) *PatchTagsIDLogsParams {
	var ()
	return &PatchTagsIDLogsParams{
		HTTPClient: client,
	}
}

/*PatchTagsIDLogsParams contains all the parameters to send to the API endpoint
for the patch tags ID logs operation typically these are written to a http.Request
*/
type PatchTagsIDLogsParams struct {

	/*LinkLogToTagDto*/
	LinkLogToTagDto *models.LinkLogToTagDto
	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch tags ID logs params
func (o *PatchTagsIDLogsParams) WithTimeout(timeout time.Duration) *PatchTagsIDLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch tags ID logs params
func (o *PatchTagsIDLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch tags ID logs params
func (o *PatchTagsIDLogsParams) WithContext(ctx context.Context) *PatchTagsIDLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch tags ID logs params
func (o *PatchTagsIDLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch tags ID logs params
func (o *PatchTagsIDLogsParams) WithHTTPClient(client *http.Client) *PatchTagsIDLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch tags ID logs params
func (o *PatchTagsIDLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLinkLogToTagDto adds the linkLogToTagDto to the patch tags ID logs params
func (o *PatchTagsIDLogsParams) WithLinkLogToTagDto(linkLogToTagDto *models.LinkLogToTagDto) *PatchTagsIDLogsParams {
	o.SetLinkLogToTagDto(linkLogToTagDto)
	return o
}

// SetLinkLogToTagDto adds the linkLogToTagDto to the patch tags ID logs params
func (o *PatchTagsIDLogsParams) SetLinkLogToTagDto(linkLogToTagDto *models.LinkLogToTagDto) {
	o.LinkLogToTagDto = linkLogToTagDto
}

// WithID adds the id to the patch tags ID logs params
func (o *PatchTagsIDLogsParams) WithID(id int64) *PatchTagsIDLogsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch tags ID logs params
func (o *PatchTagsIDLogsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchTagsIDLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.LinkLogToTagDto != nil {
		if err := r.SetBodyParam(o.LinkLogToTagDto); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
