// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SoftwareForScience/jiskefet-api-go/models"
)

// NewPostTagsParams creates a new PostTagsParams object
// with the default values initialized.
func NewPostTagsParams() *PostTagsParams {
	var ()
	return &PostTagsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostTagsParamsWithTimeout creates a new PostTagsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostTagsParamsWithTimeout(timeout time.Duration) *PostTagsParams {
	var ()
	return &PostTagsParams{

		timeout: timeout,
	}
}

// NewPostTagsParamsWithContext creates a new PostTagsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostTagsParamsWithContext(ctx context.Context) *PostTagsParams {
	var ()
	return &PostTagsParams{

		Context: ctx,
	}
}

// NewPostTagsParamsWithHTTPClient creates a new PostTagsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostTagsParamsWithHTTPClient(client *http.Client) *PostTagsParams {
	var ()
	return &PostTagsParams{
		HTTPClient: client,
	}
}

/*PostTagsParams contains all the parameters to send to the API endpoint
for the post tags operation typically these are written to a http.Request
*/
type PostTagsParams struct {

	/*CreateTagDto*/
	CreateTagDto *models.CreateTagDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post tags params
func (o *PostTagsParams) WithTimeout(timeout time.Duration) *PostTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post tags params
func (o *PostTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post tags params
func (o *PostTagsParams) WithContext(ctx context.Context) *PostTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post tags params
func (o *PostTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post tags params
func (o *PostTagsParams) WithHTTPClient(client *http.Client) *PostTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post tags params
func (o *PostTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateTagDto adds the createTagDto to the post tags params
func (o *PostTagsParams) WithCreateTagDto(createTagDto *models.CreateTagDto) *PostTagsParams {
	o.SetCreateTagDto(createTagDto)
	return o
}

// SetCreateTagDto adds the createTagDto to the post tags params
func (o *PostTagsParams) SetCreateTagDto(createTagDto *models.CreateTagDto) {
	o.CreateTagDto = createTagDto
}

// WriteToRequest writes these params to a swagger request
func (o *PostTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateTagDto != nil {
		if err := r.SetBodyParam(o.CreateTagDto); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
