// Code generated by go-swagger; DO NOT EDIT.

package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAttachmentsIDLogsReader is a Reader for the GetAttachmentsIDLogs structure.
type GetAttachmentsIDLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAttachmentsIDLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAttachmentsIDLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetAttachmentsIDLogsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAttachmentsIDLogsOK creates a GetAttachmentsIDLogsOK with default headers values
func NewGetAttachmentsIDLogsOK() *GetAttachmentsIDLogsOK {
	return &GetAttachmentsIDLogsOK{}
}

/*GetAttachmentsIDLogsOK handles this case with default header values.

Succesfully returned the Attachments.
*/
type GetAttachmentsIDLogsOK struct {
}

func (o *GetAttachmentsIDLogsOK) Error() string {
	return fmt.Sprintf("[GET /attachments/{id}/logs][%d] getAttachmentsIdLogsOK ", 200)
}

func (o *GetAttachmentsIDLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAttachmentsIDLogsNotFound creates a GetAttachmentsIDLogsNotFound with default headers values
func NewGetAttachmentsIDLogsNotFound() *GetAttachmentsIDLogsNotFound {
	return &GetAttachmentsIDLogsNotFound{}
}

/*GetAttachmentsIDLogsNotFound handles this case with default header values.

No Attachments found for this Log.
*/
type GetAttachmentsIDLogsNotFound struct {
}

func (o *GetAttachmentsIDLogsNotFound) Error() string {
	return fmt.Sprintf("[GET /attachments/{id}/logs][%d] getAttachmentsIdLogsNotFound ", 404)
}

func (o *GetAttachmentsIDLogsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
