// Code generated by go-swagger; DO NOT EDIT.

package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostAttachmentsReader is a Reader for the PostAttachments structure.
type PostAttachmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAttachmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostAttachmentsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAttachmentsCreated creates a PostAttachmentsCreated with default headers values
func NewPostAttachmentsCreated() *PostAttachmentsCreated {
	return &PostAttachmentsCreated{}
}

/*PostAttachmentsCreated handles this case with default header values.

PostAttachmentsCreated post attachments created
*/
type PostAttachmentsCreated struct {
	Payload interface{}
}

func (o *PostAttachmentsCreated) Error() string {
	return fmt.Sprintf("[POST /attachments][%d] postAttachmentsCreated  %+v", 201, o.Payload)
}

func (o *PostAttachmentsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
