// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAuthReader is a Reader for the GetAuth structure.
type GetAuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAuthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetAuthUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewGetAuthUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAuthOK creates a GetAuthOK with default headers values
func NewGetAuthOK() *GetAuthOK {
	return &GetAuthOK{}
}

/*GetAuthOK handles this case with default header values.

User has successfully authenticated and a JWT has been given as a response.
*/
type GetAuthOK struct {
	Payload string
}

func (o *GetAuthOK) Error() string {
	return fmt.Sprintf("[GET /auth][%d] getAuthOK  %+v", 200, o.Payload)
}

func (o *GetAuthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAuthUnauthorized creates a GetAuthUnauthorized with default headers values
func NewGetAuthUnauthorized() *GetAuthUnauthorized {
	return &GetAuthUnauthorized{}
}

/*GetAuthUnauthorized handles this case with default header values.

User is unauthorized due to an invalid Authorization Grant.
*/
type GetAuthUnauthorized struct {
}

func (o *GetAuthUnauthorized) Error() string {
	return fmt.Sprintf("[GET /auth][%d] getAuthUnauthorized ", 401)
}

func (o *GetAuthUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAuthUnprocessableEntity creates a GetAuthUnprocessableEntity with default headers values
func NewGetAuthUnprocessableEntity() *GetAuthUnprocessableEntity {
	return &GetAuthUnprocessableEntity{}
}

/*GetAuthUnprocessableEntity handles this case with default header values.

User has not provided an Authorization Grant as a query parameter.
*/
type GetAuthUnprocessableEntity struct {
}

func (o *GetAuthUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /auth][%d] getAuthUnprocessableEntity ", 422)
}

func (o *GetAuthUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
