// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetUsersIDTokensReader is a Reader for the GetUsersIDTokens structure.
type GetUsersIDTokensReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersIDTokensReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUsersIDTokensOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetUsersIDTokensNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUsersIDTokensOK creates a GetUsersIDTokensOK with default headers values
func NewGetUsersIDTokensOK() *GetUsersIDTokensOK {
	return &GetUsersIDTokensOK{}
}

/*GetUsersIDTokensOK handles this case with default header values.

Succesfully returned all Tokens.
*/
type GetUsersIDTokensOK struct {
}

func (o *GetUsersIDTokensOK) Error() string {
	return fmt.Sprintf("[GET /users/{id}/tokens][%d] getUsersIdTokensOK ", 200)
}

func (o *GetUsersIDTokensOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUsersIDTokensNotFound creates a GetUsersIDTokensNotFound with default headers values
func NewGetUsersIDTokensNotFound() *GetUsersIDTokensNotFound {
	return &GetUsersIDTokensNotFound{}
}

/*GetUsersIDTokensNotFound handles this case with default header values.

Unable to find Tokens with given User ID
*/
type GetUsersIDTokensNotFound struct {
}

func (o *GetUsersIDTokensNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{id}/tokens][%d] getUsersIdTokensNotFound ", 404)
}

func (o *GetUsersIDTokensNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
