// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetUsersIDLogsReader is a Reader for the GetUsersIDLogs structure.
type GetUsersIDLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersIDLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUsersIDLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetUsersIDLogsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUsersIDLogsOK creates a GetUsersIDLogsOK with default headers values
func NewGetUsersIDLogsOK() *GetUsersIDLogsOK {
	return &GetUsersIDLogsOK{}
}

/*GetUsersIDLogsOK handles this case with default header values.

Succesfully returned Logs.
*/
type GetUsersIDLogsOK struct {
}

func (o *GetUsersIDLogsOK) Error() string {
	return fmt.Sprintf("[GET /users/{id}/logs][%d] getUsersIdLogsOK ", 200)
}

func (o *GetUsersIDLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUsersIDLogsNotFound creates a GetUsersIDLogsNotFound with default headers values
func NewGetUsersIDLogsNotFound() *GetUsersIDLogsNotFound {
	return &GetUsersIDLogsNotFound{}
}

/*GetUsersIDLogsNotFound handles this case with default header values.

No Logs found for this User.
*/
type GetUsersIDLogsNotFound struct {
}

func (o *GetUsersIDLogsNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{id}/logs][%d] getUsersIdLogsNotFound ", 404)
}

func (o *GetUsersIDLogsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
