// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetUsersIDLogsReader is a Reader for the GetUsersIDLogs structure.
type GetUsersIDLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersIDLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUsersIDLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUsersIDLogsOK creates a GetUsersIDLogsOK with default headers values
func NewGetUsersIDLogsOK() *GetUsersIDLogsOK {
	return &GetUsersIDLogsOK{}
}

/*GetUsersIDLogsOK handles this case with default header values.

GetUsersIDLogsOK get users Id logs o k
*/
type GetUsersIDLogsOK struct {
	Payload interface{}
}

func (o *GetUsersIDLogsOK) Error() string {
	return fmt.Sprintf("[GET /users/{id}/logs][%d] getUsersIdLogsOK  %+v", 200, o.Payload)
}

func (o *GetUsersIDLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
