// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostUsersIDTokensReader is a Reader for the PostUsersIDTokens structure.
type PostUsersIDTokensReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostUsersIDTokensReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostUsersIDTokensCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostUsersIDTokensCreated creates a PostUsersIDTokensCreated with default headers values
func NewPostUsersIDTokensCreated() *PostUsersIDTokensCreated {
	return &PostUsersIDTokensCreated{}
}

/*PostUsersIDTokensCreated handles this case with default header values.

PostUsersIDTokensCreated post users Id tokens created
*/
type PostUsersIDTokensCreated struct {
	Payload interface{}
}

func (o *PostUsersIDTokensCreated) Error() string {
	return fmt.Sprintf("[POST /users/{id}/tokens][%d] postUsersIdTokensCreated  %+v", 201, o.Payload)
}

func (o *PostUsersIDTokensCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
