// Code generated by go-swagger; DO NOT EDIT.

package subsystems

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSubsystemsIDReader is a Reader for the GetSubsystemsID structure.
type GetSubsystemsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSubsystemsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSubsystemsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSubsystemsIDOK creates a GetSubsystemsIDOK with default headers values
func NewGetSubsystemsIDOK() *GetSubsystemsIDOK {
	return &GetSubsystemsIDOK{}
}

/*GetSubsystemsIDOK handles this case with default header values.

OK
*/
type GetSubsystemsIDOK struct {
	Payload interface{}
}

func (o *GetSubsystemsIDOK) Error() string {
	return fmt.Sprintf("[GET /subsystems/{id}][%d] getSubsystemsIdOK  %+v", 200, o.Payload)
}

func (o *GetSubsystemsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
