// Code generated by go-swagger; DO NOT EDIT.

package subsystems

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSubsystemsReader is a Reader for the GetSubsystems structure.
type GetSubsystemsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSubsystemsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSubsystemsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetSubsystemsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSubsystemsOK creates a GetSubsystemsOK with default headers values
func NewGetSubsystemsOK() *GetSubsystemsOK {
	return &GetSubsystemsOK{}
}

/*GetSubsystemsOK handles this case with default header values.

Succesfully returned Subsystems.
*/
type GetSubsystemsOK struct {
}

func (o *GetSubsystemsOK) Error() string {
	return fmt.Sprintf("[GET /subsystems][%d] getSubsystemsOK ", 200)
}

func (o *GetSubsystemsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSubsystemsNotFound creates a GetSubsystemsNotFound with default headers values
func NewGetSubsystemsNotFound() *GetSubsystemsNotFound {
	return &GetSubsystemsNotFound{}
}

/*GetSubsystemsNotFound handles this case with default header values.

No Subsystems found.
*/
type GetSubsystemsNotFound struct {
}

func (o *GetSubsystemsNotFound) Error() string {
	return fmt.Sprintf("[GET /subsystems][%d] getSubsystemsNotFound ", 404)
}

func (o *GetSubsystemsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
