// Code generated by go-swagger; DO NOT EDIT.

package subsystems

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSubsystemsParams creates a new GetSubsystemsParams object
// with the default values initialized.
func NewGetSubsystemsParams() *GetSubsystemsParams {

	return &GetSubsystemsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSubsystemsParamsWithTimeout creates a new GetSubsystemsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSubsystemsParamsWithTimeout(timeout time.Duration) *GetSubsystemsParams {

	return &GetSubsystemsParams{

		timeout: timeout,
	}
}

// NewGetSubsystemsParamsWithContext creates a new GetSubsystemsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSubsystemsParamsWithContext(ctx context.Context) *GetSubsystemsParams {

	return &GetSubsystemsParams{

		Context: ctx,
	}
}

// NewGetSubsystemsParamsWithHTTPClient creates a new GetSubsystemsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSubsystemsParamsWithHTTPClient(client *http.Client) *GetSubsystemsParams {

	return &GetSubsystemsParams{
		HTTPClient: client,
	}
}

/*GetSubsystemsParams contains all the parameters to send to the API endpoint
for the get subsystems operation typically these are written to a http.Request
*/
type GetSubsystemsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get subsystems params
func (o *GetSubsystemsParams) WithTimeout(timeout time.Duration) *GetSubsystemsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get subsystems params
func (o *GetSubsystemsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get subsystems params
func (o *GetSubsystemsParams) WithContext(ctx context.Context) *GetSubsystemsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get subsystems params
func (o *GetSubsystemsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get subsystems params
func (o *GetSubsystemsParams) WithHTTPClient(client *http.Client) *GetSubsystemsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get subsystems params
func (o *GetSubsystemsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSubsystemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
