// Code generated by go-swagger; DO NOT EDIT.

package subsystems

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new subsystems API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for subsystems API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetSubsystems get subsystems API
*/
func (a *Client) GetSubsystems(params *GetSubsystemsParams, authInfo runtime.ClientAuthInfoWriter) (*GetSubsystemsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSubsystemsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetSubsystems",
		Method:             "GET",
		PathPattern:        "/subsystems",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetSubsystemsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSubsystemsOK), nil

}

/*
GetSubsystemsID get subsystems ID API
*/
func (a *Client) GetSubsystemsID(params *GetSubsystemsIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetSubsystemsIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSubsystemsIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetSubsystemsID",
		Method:             "GET",
		PathPattern:        "/subsystems/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetSubsystemsIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSubsystemsIDOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
