// Code generated by go-swagger; DO NOT EDIT.

package overview

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetOverviewReader is a Reader for the GetOverview structure.
type GetOverviewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOverviewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetOverviewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOverviewOK creates a GetOverviewOK with default headers values
func NewGetOverviewOK() *GetOverviewOK {
	return &GetOverviewOK{}
}

/*GetOverviewOK handles this case with default header values.

OK
*/
type GetOverviewOK struct {
	Payload string
}

func (o *GetOverviewOK) Error() string {
	return fmt.Sprintf("[GET /overview][%d] getOverviewOK  %+v", 200, o.Payload)
}

func (o *GetOverviewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
