// Code generated by go-swagger; DO NOT EDIT.

package flp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostFlpReader is a Reader for the PostFlp structure.
type PostFlpReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostFlpReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostFlpCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostFlpCreated creates a PostFlpCreated with default headers values
func NewPostFlpCreated() *PostFlpCreated {
	return &PostFlpCreated{}
}

/*PostFlpCreated handles this case with default header values.

PostFlpCreated post flp created
*/
type PostFlpCreated struct {
	Payload interface{}
}

func (o *PostFlpCreated) Error() string {
	return fmt.Sprintf("[POST /flp][%d] postFlpCreated  %+v", 201, o.Payload)
}

func (o *PostFlpCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
