// Code generated by go-swagger; DO NOT EDIT.

package flp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostFlpReader is a Reader for the PostFlp structure.
type PostFlpReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostFlpReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostFlpCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPostFlpConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostFlpCreated creates a PostFlpCreated with default headers values
func NewPostFlpCreated() *PostFlpCreated {
	return &PostFlpCreated{}
}

/*PostFlpCreated handles this case with default header values.

Succesfully created an FLP.
*/
type PostFlpCreated struct {
}

func (o *PostFlpCreated) Error() string {
	return fmt.Sprintf("[POST /flp][%d] postFlpCreated ", 201)
}

func (o *PostFlpCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostFlpConflict creates a PostFlpConflict with default headers values
func NewPostFlpConflict() *PostFlpConflict {
	return &PostFlpConflict{}
}

/*PostFlpConflict handles this case with default header values.

An FLP already exists with this Name and Hostname.
*/
type PostFlpConflict struct {
}

func (o *PostFlpConflict) Error() string {
	return fmt.Sprintf("[POST /flp][%d] postFlpConflict ", 409)
}

func (o *PostFlpConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
