// Code generated by go-swagger; DO NOT EDIT.

package flp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SoftwareForScience/jiskefet-api-go/models"
)

// NewPostFlpParams creates a new PostFlpParams object
// with the default values initialized.
func NewPostFlpParams() *PostFlpParams {
	var ()
	return &PostFlpParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostFlpParamsWithTimeout creates a new PostFlpParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostFlpParamsWithTimeout(timeout time.Duration) *PostFlpParams {
	var ()
	return &PostFlpParams{

		timeout: timeout,
	}
}

// NewPostFlpParamsWithContext creates a new PostFlpParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostFlpParamsWithContext(ctx context.Context) *PostFlpParams {
	var ()
	return &PostFlpParams{

		Context: ctx,
	}
}

// NewPostFlpParamsWithHTTPClient creates a new PostFlpParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostFlpParamsWithHTTPClient(client *http.Client) *PostFlpParams {
	var ()
	return &PostFlpParams{
		HTTPClient: client,
	}
}

/*PostFlpParams contains all the parameters to send to the API endpoint
for the post flp operation typically these are written to a http.Request
*/
type PostFlpParams struct {

	/*CreateFlpDto*/
	CreateFlpDto *models.CreateFlpDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post flp params
func (o *PostFlpParams) WithTimeout(timeout time.Duration) *PostFlpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post flp params
func (o *PostFlpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post flp params
func (o *PostFlpParams) WithContext(ctx context.Context) *PostFlpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post flp params
func (o *PostFlpParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post flp params
func (o *PostFlpParams) WithHTTPClient(client *http.Client) *PostFlpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post flp params
func (o *PostFlpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateFlpDto adds the createFlpDto to the post flp params
func (o *PostFlpParams) WithCreateFlpDto(createFlpDto *models.CreateFlpDto) *PostFlpParams {
	o.SetCreateFlpDto(createFlpDto)
	return o
}

// SetCreateFlpDto adds the createFlpDto to the post flp params
func (o *PostFlpParams) SetCreateFlpDto(createFlpDto *models.CreateFlpDto) {
	o.CreateFlpDto = createFlpDto
}

// WriteToRequest writes these params to a swagger request
func (o *PostFlpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateFlpDto != nil {
		if err := r.SetBodyParam(o.CreateFlpDto); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
