// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLogsIDThreadsParams creates a new GetLogsIDThreadsParams object
// with the default values initialized.
func NewGetLogsIDThreadsParams() *GetLogsIDThreadsParams {
	var ()
	return &GetLogsIDThreadsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLogsIDThreadsParamsWithTimeout creates a new GetLogsIDThreadsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLogsIDThreadsParamsWithTimeout(timeout time.Duration) *GetLogsIDThreadsParams {
	var ()
	return &GetLogsIDThreadsParams{

		timeout: timeout,
	}
}

// NewGetLogsIDThreadsParamsWithContext creates a new GetLogsIDThreadsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLogsIDThreadsParamsWithContext(ctx context.Context) *GetLogsIDThreadsParams {
	var ()
	return &GetLogsIDThreadsParams{

		Context: ctx,
	}
}

// NewGetLogsIDThreadsParamsWithHTTPClient creates a new GetLogsIDThreadsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLogsIDThreadsParamsWithHTTPClient(client *http.Client) *GetLogsIDThreadsParams {
	var ()
	return &GetLogsIDThreadsParams{
		HTTPClient: client,
	}
}

/*GetLogsIDThreadsParams contains all the parameters to send to the API endpoint
for the get logs ID threads operation typically these are written to a http.Request
*/
type GetLogsIDThreadsParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get logs ID threads params
func (o *GetLogsIDThreadsParams) WithTimeout(timeout time.Duration) *GetLogsIDThreadsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get logs ID threads params
func (o *GetLogsIDThreadsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get logs ID threads params
func (o *GetLogsIDThreadsParams) WithContext(ctx context.Context) *GetLogsIDThreadsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get logs ID threads params
func (o *GetLogsIDThreadsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get logs ID threads params
func (o *GetLogsIDThreadsParams) WithHTTPClient(client *http.Client) *GetLogsIDThreadsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get logs ID threads params
func (o *GetLogsIDThreadsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get logs ID threads params
func (o *GetLogsIDThreadsParams) WithID(id int64) *GetLogsIDThreadsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get logs ID threads params
func (o *GetLogsIDThreadsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetLogsIDThreadsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
