// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLogsIDParams creates a new GetLogsIDParams object
// with the default values initialized.
func NewGetLogsIDParams() *GetLogsIDParams {
	var ()
	return &GetLogsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLogsIDParamsWithTimeout creates a new GetLogsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLogsIDParamsWithTimeout(timeout time.Duration) *GetLogsIDParams {
	var ()
	return &GetLogsIDParams{

		timeout: timeout,
	}
}

// NewGetLogsIDParamsWithContext creates a new GetLogsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLogsIDParamsWithContext(ctx context.Context) *GetLogsIDParams {
	var ()
	return &GetLogsIDParams{

		Context: ctx,
	}
}

// NewGetLogsIDParamsWithHTTPClient creates a new GetLogsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLogsIDParamsWithHTTPClient(client *http.Client) *GetLogsIDParams {
	var ()
	return &GetLogsIDParams{
		HTTPClient: client,
	}
}

/*GetLogsIDParams contains all the parameters to send to the API endpoint
for the get logs ID operation typically these are written to a http.Request
*/
type GetLogsIDParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get logs ID params
func (o *GetLogsIDParams) WithTimeout(timeout time.Duration) *GetLogsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get logs ID params
func (o *GetLogsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get logs ID params
func (o *GetLogsIDParams) WithContext(ctx context.Context) *GetLogsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get logs ID params
func (o *GetLogsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get logs ID params
func (o *GetLogsIDParams) WithHTTPClient(client *http.Client) *GetLogsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get logs ID params
func (o *GetLogsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get logs ID params
func (o *GetLogsIDParams) WithID(id int64) *GetLogsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get logs ID params
func (o *GetLogsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetLogsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
