// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new logs API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for logs API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetLogs returns all logs
*/
func (a *Client) GetLogs(params *GetLogsParams, authInfo runtime.ClientAuthInfoWriter) (*GetLogsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLogsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetLogs",
		Method:             "GET",
		PathPattern:        "/logs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetLogsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetLogsOK), nil

}

/*
GetLogsID returns a specific log
*/
func (a *Client) GetLogsID(params *GetLogsIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetLogsIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLogsIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetLogsID",
		Method:             "GET",
		PathPattern:        "/logs/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetLogsIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetLogsIDOK), nil

}

/*
GetLogsIDThreads get logs ID threads API
*/
func (a *Client) GetLogsIDThreads(params *GetLogsIDThreadsParams, authInfo runtime.ClientAuthInfoWriter) (*GetLogsIDThreadsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLogsIDThreadsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetLogsIDThreads",
		Method:             "GET",
		PathPattern:        "/logs/{id}/threads",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetLogsIDThreadsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetLogsIDThreadsOK), nil

}

/*
PatchLogsIDRuns links a run to a specific log
*/
func (a *Client) PatchLogsIDRuns(params *PatchLogsIDRunsParams, authInfo runtime.ClientAuthInfoWriter) (*PatchLogsIDRunsNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchLogsIDRunsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PatchLogsIDRuns",
		Method:             "PATCH",
		PathPattern:        "/logs/{id}/runs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PatchLogsIDRunsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PatchLogsIDRunsNoContent), nil

}

/*
PostLogs creates a log
*/
func (a *Client) PostLogs(params *PostLogsParams, authInfo runtime.ClientAuthInfoWriter) (*PostLogsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostLogsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostLogs",
		Method:             "POST",
		PathPattern:        "/logs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostLogsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostLogsCreated), nil

}

/*
PostLogsIDAttachments creates a attachment for a specific log
*/
func (a *Client) PostLogsIDAttachments(params *PostLogsIDAttachmentsParams, authInfo runtime.ClientAuthInfoWriter) (*PostLogsIDAttachmentsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostLogsIDAttachmentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostLogsIDAttachments",
		Method:             "POST",
		PathPattern:        "/logs/{id}/attachments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostLogsIDAttachmentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostLogsIDAttachmentsCreated), nil

}

/*
PostLogsThreads post logs threads API
*/
func (a *Client) PostLogsThreads(params *PostLogsThreadsParams, authInfo runtime.ClientAuthInfoWriter) (*PostLogsThreadsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostLogsThreadsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostLogsThreads",
		Method:             "POST",
		PathPattern:        "/logs/threads",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostLogsThreadsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostLogsThreadsCreated), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
