// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SoftwareForScience/jiskefet-api-go/models"
)

// NewPostLogsThreadsParams creates a new PostLogsThreadsParams object
// with the default values initialized.
func NewPostLogsThreadsParams() *PostLogsThreadsParams {
	var ()
	return &PostLogsThreadsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLogsThreadsParamsWithTimeout creates a new PostLogsThreadsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLogsThreadsParamsWithTimeout(timeout time.Duration) *PostLogsThreadsParams {
	var ()
	return &PostLogsThreadsParams{

		timeout: timeout,
	}
}

// NewPostLogsThreadsParamsWithContext creates a new PostLogsThreadsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLogsThreadsParamsWithContext(ctx context.Context) *PostLogsThreadsParams {
	var ()
	return &PostLogsThreadsParams{

		Context: ctx,
	}
}

// NewPostLogsThreadsParamsWithHTTPClient creates a new PostLogsThreadsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLogsThreadsParamsWithHTTPClient(client *http.Client) *PostLogsThreadsParams {
	var ()
	return &PostLogsThreadsParams{
		HTTPClient: client,
	}
}

/*PostLogsThreadsParams contains all the parameters to send to the API endpoint
for the post logs threads operation typically these are written to a http.Request
*/
type PostLogsThreadsParams struct {

	/*CreateCommentDto*/
	CreateCommentDto *models.CreateCommentDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post logs threads params
func (o *PostLogsThreadsParams) WithTimeout(timeout time.Duration) *PostLogsThreadsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post logs threads params
func (o *PostLogsThreadsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post logs threads params
func (o *PostLogsThreadsParams) WithContext(ctx context.Context) *PostLogsThreadsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post logs threads params
func (o *PostLogsThreadsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post logs threads params
func (o *PostLogsThreadsParams) WithHTTPClient(client *http.Client) *PostLogsThreadsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post logs threads params
func (o *PostLogsThreadsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateCommentDto adds the createCommentDto to the post logs threads params
func (o *PostLogsThreadsParams) WithCreateCommentDto(createCommentDto *models.CreateCommentDto) *PostLogsThreadsParams {
	o.SetCreateCommentDto(createCommentDto)
	return o
}

// SetCreateCommentDto adds the createCommentDto to the post logs threads params
func (o *PostLogsThreadsParams) SetCreateCommentDto(createCommentDto *models.CreateCommentDto) {
	o.CreateCommentDto = createCommentDto
}

// WriteToRequest writes these params to a swagger request
func (o *PostLogsThreadsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateCommentDto != nil {
		if err := r.SetBodyParam(o.CreateCommentDto); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
