// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostLogsThreadsReader is a Reader for the PostLogsThreads structure.
type PostLogsThreadsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLogsThreadsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostLogsThreadsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLogsThreadsCreated creates a PostLogsThreadsCreated with default headers values
func NewPostLogsThreadsCreated() *PostLogsThreadsCreated {
	return &PostLogsThreadsCreated{}
}

/*PostLogsThreadsCreated handles this case with default header values.

PostLogsThreadsCreated post logs threads created
*/
type PostLogsThreadsCreated struct {
}

func (o *PostLogsThreadsCreated) Error() string {
	return fmt.Sprintf("[POST /logs/threads][%d] postLogsThreadsCreated ", 201)
}

func (o *PostLogsThreadsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
