// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SoftwareForScience/jiskefet-api-go/models"
)

// NewPostLogsIDAttachmentsParams creates a new PostLogsIDAttachmentsParams object
// with the default values initialized.
func NewPostLogsIDAttachmentsParams() *PostLogsIDAttachmentsParams {
	var ()
	return &PostLogsIDAttachmentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLogsIDAttachmentsParamsWithTimeout creates a new PostLogsIDAttachmentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLogsIDAttachmentsParamsWithTimeout(timeout time.Duration) *PostLogsIDAttachmentsParams {
	var ()
	return &PostLogsIDAttachmentsParams{

		timeout: timeout,
	}
}

// NewPostLogsIDAttachmentsParamsWithContext creates a new PostLogsIDAttachmentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLogsIDAttachmentsParamsWithContext(ctx context.Context) *PostLogsIDAttachmentsParams {
	var ()
	return &PostLogsIDAttachmentsParams{

		Context: ctx,
	}
}

// NewPostLogsIDAttachmentsParamsWithHTTPClient creates a new PostLogsIDAttachmentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLogsIDAttachmentsParamsWithHTTPClient(client *http.Client) *PostLogsIDAttachmentsParams {
	var ()
	return &PostLogsIDAttachmentsParams{
		HTTPClient: client,
	}
}

/*PostLogsIDAttachmentsParams contains all the parameters to send to the API endpoint
for the post logs ID attachments operation typically these are written to a http.Request
*/
type PostLogsIDAttachmentsParams struct {

	/*CreateAttachmentDto*/
	CreateAttachmentDto *models.CreateAttachmentDto
	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post logs ID attachments params
func (o *PostLogsIDAttachmentsParams) WithTimeout(timeout time.Duration) *PostLogsIDAttachmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post logs ID attachments params
func (o *PostLogsIDAttachmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post logs ID attachments params
func (o *PostLogsIDAttachmentsParams) WithContext(ctx context.Context) *PostLogsIDAttachmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post logs ID attachments params
func (o *PostLogsIDAttachmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post logs ID attachments params
func (o *PostLogsIDAttachmentsParams) WithHTTPClient(client *http.Client) *PostLogsIDAttachmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post logs ID attachments params
func (o *PostLogsIDAttachmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateAttachmentDto adds the createAttachmentDto to the post logs ID attachments params
func (o *PostLogsIDAttachmentsParams) WithCreateAttachmentDto(createAttachmentDto *models.CreateAttachmentDto) *PostLogsIDAttachmentsParams {
	o.SetCreateAttachmentDto(createAttachmentDto)
	return o
}

// SetCreateAttachmentDto adds the createAttachmentDto to the post logs ID attachments params
func (o *PostLogsIDAttachmentsParams) SetCreateAttachmentDto(createAttachmentDto *models.CreateAttachmentDto) {
	o.CreateAttachmentDto = createAttachmentDto
}

// WithID adds the id to the post logs ID attachments params
func (o *PostLogsIDAttachmentsParams) WithID(id int64) *PostLogsIDAttachmentsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post logs ID attachments params
func (o *PostLogsIDAttachmentsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostLogsIDAttachmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateAttachmentDto != nil {
		if err := r.SetBodyParam(o.CreateAttachmentDto); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
