// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SoftwareForScience/jiskefet-api-go/models"
)

// NewPostLogsParams creates a new PostLogsParams object
// with the default values initialized.
func NewPostLogsParams() *PostLogsParams {
	var ()
	return &PostLogsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLogsParamsWithTimeout creates a new PostLogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLogsParamsWithTimeout(timeout time.Duration) *PostLogsParams {
	var ()
	return &PostLogsParams{

		timeout: timeout,
	}
}

// NewPostLogsParamsWithContext creates a new PostLogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLogsParamsWithContext(ctx context.Context) *PostLogsParams {
	var ()
	return &PostLogsParams{

		Context: ctx,
	}
}

// NewPostLogsParamsWithHTTPClient creates a new PostLogsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLogsParamsWithHTTPClient(client *http.Client) *PostLogsParams {
	var ()
	return &PostLogsParams{
		HTTPClient: client,
	}
}

/*PostLogsParams contains all the parameters to send to the API endpoint
for the post logs operation typically these are written to a http.Request
*/
type PostLogsParams struct {

	/*CreateLogDto*/
	CreateLogDto *models.CreateLogDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post logs params
func (o *PostLogsParams) WithTimeout(timeout time.Duration) *PostLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post logs params
func (o *PostLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post logs params
func (o *PostLogsParams) WithContext(ctx context.Context) *PostLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post logs params
func (o *PostLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post logs params
func (o *PostLogsParams) WithHTTPClient(client *http.Client) *PostLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post logs params
func (o *PostLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateLogDto adds the createLogDto to the post logs params
func (o *PostLogsParams) WithCreateLogDto(createLogDto *models.CreateLogDto) *PostLogsParams {
	o.SetCreateLogDto(createLogDto)
	return o
}

// SetCreateLogDto adds the createLogDto to the post logs params
func (o *PostLogsParams) SetCreateLogDto(createLogDto *models.CreateLogDto) {
	o.CreateLogDto = createLogDto
}

// WriteToRequest writes these params to a swagger request
func (o *PostLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateLogDto != nil {
		if err := r.SetBodyParam(o.CreateLogDto); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
