// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostLogsReader is a Reader for the PostLogs structure.
type PostLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostLogsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLogsCreated creates a PostLogsCreated with default headers values
func NewPostLogsCreated() *PostLogsCreated {
	return &PostLogsCreated{}
}

/*PostLogsCreated handles this case with default header values.

PostLogsCreated post logs created
*/
type PostLogsCreated struct {
}

func (o *PostLogsCreated) Error() string {
	return fmt.Sprintf("[POST /logs][%d] postLogsCreated ", 201)
}

func (o *PostLogsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
