// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PatchRunsIDLogsReader is a Reader for the PatchRunsIDLogs structure.
type PatchRunsIDLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchRunsIDLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPatchRunsIDLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchRunsIDLogsOK creates a PatchRunsIDLogsOK with default headers values
func NewPatchRunsIDLogsOK() *PatchRunsIDLogsOK {
	return &PatchRunsIDLogsOK{}
}

/*PatchRunsIDLogsOK handles this case with default header values.

PatchRunsIDLogsOK patch runs Id logs o k
*/
type PatchRunsIDLogsOK struct {
}

func (o *PatchRunsIDLogsOK) Error() string {
	return fmt.Sprintf("[PATCH /runs/{id}/logs][%d] patchRunsIdLogsOK ", 200)
}

func (o *PatchRunsIDLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
