// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SoftwareForScience/jiskefet-api-go/models"
)

// NewPatchRunsIDParams creates a new PatchRunsIDParams object
// with the default values initialized.
func NewPatchRunsIDParams() *PatchRunsIDParams {
	var ()
	return &PatchRunsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchRunsIDParamsWithTimeout creates a new PatchRunsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchRunsIDParamsWithTimeout(timeout time.Duration) *PatchRunsIDParams {
	var ()
	return &PatchRunsIDParams{

		timeout: timeout,
	}
}

// NewPatchRunsIDParamsWithContext creates a new PatchRunsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchRunsIDParamsWithContext(ctx context.Context) *PatchRunsIDParams {
	var ()
	return &PatchRunsIDParams{

		Context: ctx,
	}
}

// NewPatchRunsIDParamsWithHTTPClient creates a new PatchRunsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchRunsIDParamsWithHTTPClient(client *http.Client) *PatchRunsIDParams {
	var ()
	return &PatchRunsIDParams{
		HTTPClient: client,
	}
}

/*PatchRunsIDParams contains all the parameters to send to the API endpoint
for the patch runs ID operation typically these are written to a http.Request
*/
type PatchRunsIDParams struct {

	/*PatchRunDto*/
	PatchRunDto *models.PatchRunDto
	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch runs ID params
func (o *PatchRunsIDParams) WithTimeout(timeout time.Duration) *PatchRunsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch runs ID params
func (o *PatchRunsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch runs ID params
func (o *PatchRunsIDParams) WithContext(ctx context.Context) *PatchRunsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch runs ID params
func (o *PatchRunsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch runs ID params
func (o *PatchRunsIDParams) WithHTTPClient(client *http.Client) *PatchRunsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch runs ID params
func (o *PatchRunsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPatchRunDto adds the patchRunDto to the patch runs ID params
func (o *PatchRunsIDParams) WithPatchRunDto(patchRunDto *models.PatchRunDto) *PatchRunsIDParams {
	o.SetPatchRunDto(patchRunDto)
	return o
}

// SetPatchRunDto adds the patchRunDto to the patch runs ID params
func (o *PatchRunsIDParams) SetPatchRunDto(patchRunDto *models.PatchRunDto) {
	o.PatchRunDto = patchRunDto
}

// WithID adds the id to the patch runs ID params
func (o *PatchRunsIDParams) WithID(id int64) *PatchRunsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch runs ID params
func (o *PatchRunsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchRunsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PatchRunDto != nil {
		if err := r.SetBodyParam(o.PatchRunDto); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
