// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PatchRunsIDReader is a Reader for the PatchRunsID structure.
type PatchRunsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchRunsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPatchRunsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchRunsIDOK creates a PatchRunsIDOK with default headers values
func NewPatchRunsIDOK() *PatchRunsIDOK {
	return &PatchRunsIDOK{}
}

/*PatchRunsIDOK handles this case with default header values.

PatchRunsIDOK patch runs Id o k
*/
type PatchRunsIDOK struct {
	Payload interface{}
}

func (o *PatchRunsIDOK) Error() string {
	return fmt.Sprintf("[PATCH /runs/{id}][%d] patchRunsIdOK  %+v", 200, o.Payload)
}

func (o *PatchRunsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
