// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateCommentDto create comment dto
// swagger:model CreateCommentDto
type CreateCommentDto struct {

	// Attachments of this log
	// Required: true
	Attachments []string `json:"attachments"`

	// Content of the comment
	// Required: true
	Body *string `json:"body"`

	// Where did the log come from?
	// Required: true
	// Enum: [human process]
	Origin *string `json:"origin"`

	// Log id of Parent comment
	// Required: true
	ParentID *int64 `json:"parentId"`

	// The id of a log
	// Required: true
	RootID *int64 `json:"rootId"`

	// What kind of log is it?
	// Required: true
	// Enum: [run subsystem announcement intervention comment]
	Subtype *string `json:"subtype"`

	// Title of the comment
	// Required: true
	Title *string `json:"title"`

	// The user's id
	// Required: true
	User *int64 `json:"user"`
}

// Validate validates this create comment dto
func (m *CreateCommentDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttachments(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBody(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrigin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParentID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRootID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubtype(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateCommentDto) validateAttachments(formats strfmt.Registry) error {

	if err := validate.Required("attachments", "body", m.Attachments); err != nil {
		return err
	}

	return nil
}

func (m *CreateCommentDto) validateBody(formats strfmt.Registry) error {

	if err := validate.Required("body", "body", m.Body); err != nil {
		return err
	}

	return nil
}

var createCommentDtoTypeOriginPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["human","process"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createCommentDtoTypeOriginPropEnum = append(createCommentDtoTypeOriginPropEnum, v)
	}
}

const (

	// CreateCommentDtoOriginHuman captures enum value "human"
	CreateCommentDtoOriginHuman string = "human"

	// CreateCommentDtoOriginProcess captures enum value "process"
	CreateCommentDtoOriginProcess string = "process"
)

// prop value enum
func (m *CreateCommentDto) validateOriginEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, createCommentDtoTypeOriginPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *CreateCommentDto) validateOrigin(formats strfmt.Registry) error {

	if err := validate.Required("origin", "body", m.Origin); err != nil {
		return err
	}

	// value enum
	if err := m.validateOriginEnum("origin", "body", *m.Origin); err != nil {
		return err
	}

	return nil
}

func (m *CreateCommentDto) validateParentID(formats strfmt.Registry) error {

	if err := validate.Required("parentId", "body", m.ParentID); err != nil {
		return err
	}

	return nil
}

func (m *CreateCommentDto) validateRootID(formats strfmt.Registry) error {

	if err := validate.Required("rootId", "body", m.RootID); err != nil {
		return err
	}

	return nil
}

var createCommentDtoTypeSubtypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["run","subsystem","announcement","intervention","comment"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createCommentDtoTypeSubtypePropEnum = append(createCommentDtoTypeSubtypePropEnum, v)
	}
}

const (

	// CreateCommentDtoSubtypeRun captures enum value "run"
	CreateCommentDtoSubtypeRun string = "run"

	// CreateCommentDtoSubtypeSubsystem captures enum value "subsystem"
	CreateCommentDtoSubtypeSubsystem string = "subsystem"

	// CreateCommentDtoSubtypeAnnouncement captures enum value "announcement"
	CreateCommentDtoSubtypeAnnouncement string = "announcement"

	// CreateCommentDtoSubtypeIntervention captures enum value "intervention"
	CreateCommentDtoSubtypeIntervention string = "intervention"

	// CreateCommentDtoSubtypeComment captures enum value "comment"
	CreateCommentDtoSubtypeComment string = "comment"
)

// prop value enum
func (m *CreateCommentDto) validateSubtypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, createCommentDtoTypeSubtypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *CreateCommentDto) validateSubtype(formats strfmt.Registry) error {

	if err := validate.Required("subtype", "body", m.Subtype); err != nil {
		return err
	}

	// value enum
	if err := m.validateSubtypeEnum("subtype", "body", *m.Subtype); err != nil {
		return err
	}

	return nil
}

func (m *CreateCommentDto) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	return nil
}

func (m *CreateCommentDto) validateUser(formats strfmt.Registry) error {

	if err := validate.Required("user", "body", m.User); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateCommentDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateCommentDto) UnmarshalBinary(b []byte) error {
	var res CreateCommentDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
