// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateAttachmentDto create attachment dto
// swagger:model CreateAttachmentDto
type CreateAttachmentDto struct {

	// creation time
	// Required: true
	// Format: date-time
	CreationTime *strfmt.DateTime `json:"creationTime"`

	// The base64 encoded file data.
	// Required: true
	FileData *string `json:"fileData"`

	// What kind of file is it?
	// Required: true
	FileMime *string `json:"fileMime"`

	// Name of the uploaded file.
	// Required: true
	FileName *string `json:"fileName"`

	// What is the name of the file?
	Title string `json:"title,omitempty"`
}

// Validate validates this create attachment dto
func (m *CreateAttachmentDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreationTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFileData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFileMime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFileName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateAttachmentDto) validateCreationTime(formats strfmt.Registry) error {

	if err := validate.Required("creationTime", "body", m.CreationTime); err != nil {
		return err
	}

	if err := validate.FormatOf("creationTime", "body", "date-time", m.CreationTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CreateAttachmentDto) validateFileData(formats strfmt.Registry) error {

	if err := validate.Required("fileData", "body", m.FileData); err != nil {
		return err
	}

	return nil
}

func (m *CreateAttachmentDto) validateFileMime(formats strfmt.Registry) error {

	if err := validate.Required("fileMime", "body", m.FileMime); err != nil {
		return err
	}

	return nil
}

func (m *CreateAttachmentDto) validateFileName(formats strfmt.Registry) error {

	if err := validate.Required("fileName", "body", m.FileName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateAttachmentDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateAttachmentDto) UnmarshalBinary(b []byte) error {
	var res CreateAttachmentDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
