// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SubSystem sub system
// swagger:model SubSystem
type SubSystem struct {

	// subsystem Id
	// Required: true
	SubsystemID *int64 `json:"subsystemId"`
}

// Validate validates this sub system
func (m *SubSystem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubsystemID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubSystem) validateSubsystemID(formats strfmt.Registry) error {

	if err := validate.Required("subsystemId", "body", m.SubsystemID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SubSystem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubSystem) UnmarshalBinary(b []byte) error {
	var res SubSystem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
